[tool.poetry]
name = "aoc2023"
version = "0.1.0"
description = ""
authors = ["Mietzsche <mitch_hollander@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
